### PR TITLE
Master

### PR DESCRIPTION
**Pull request by algruenwald**
- TFS 2015 support
- NON VSO Notification Image & ChangeLog reference fix

### CODE REVIEW

**Comment by jcoutch** [comment]
Thanks for the fixes!  When I get a chance (hopefully in the next day or so), I'll test it out and push a new version to the Chrome store.

**Comment by algruenwald** [comment]
The size of the notification's image is a bit magic but it should be sized to 144px

**Comment by algruenwald** [comment]
Could you please merge the changes and update the Version in the Chrome-Store?

**Comment by jcoutch** [comment]
Sorry for the delay.  Due to my day-to-day job, I've fallen behind on managing my various open-source projects.  I'm going to try and set aside some time tonight to get a new version out.  If not tonight, then definitely this weekend.

**Comment by algruenwald** [comment]
I'm going to publish a forked version of TFSChatExtensions if that's ok for you

**Comment by jcoutch** [comment]
I am soooo sorry...the past couple months have been pretty crazy.  Hold off on creating the fork...I'll check this out during lunch today (around 11:30-12:30 EST), and if everything looks good, will push a new version out immediately.

**Comment by jcoutch** [comment]
So, while I did merge this in and it may fix things for on-premise TFS, it breaks when using VSO.  From what I can tell, each collection has it's own unique subdomain, uses DefaultCollection in url's, but the collectionName is the subdomain.

So if you have a project at testproject.visualstudio.com, URL's would look like this:
https://testproject.visualstudio.com/DefaultCollection/_versionControl/changeset/1234?collectionName=testproject

I'm going to code up something real quick that will detect if the TLD is visualstudio.com, and switch on/off your logic.

**Comment by jcoutch** [comment]
Changes have been pushed, and I just dropped a new version of the extension in the store.  I did notice what I think was a small bug w/ the changeset url's for on-premise instances...if you could test that and let me know if my fix worked, that'd be great.  If not (and you have time to fix it), submit a pull request with the fix.  I promise I'll be a bit more responsive from now on :-).

**Pull request merged**
