### PR TITLE
Added support of virtual directories[extension loading].

### PR DESCRIPTION
**Pull request by NikGovorov**
Support of `http://tfs.contoso.com/tfs/_rooms#RoomName` like urls.

### CODE REVIEW

**Comment by jcoutch** [comment]
I'm not sure the *\* does anything, at least based on the pattern expressions listed here: https://developer.chrome.com/extensions/match_patterns

I'm going to change it to:
`"matches": ["*://*/_rooms*", "*://*/*/_rooms*"]`
which should match on both VSO and instances where there's a virtual directory.

**Comment by jcoutch** [comment]
Fixed manifest in commits 598644c and e2bb2b74.  Thanks for letting me know about the virtual directory issue!

**Comment by eskitek** [comment]
Hi there. I just ran into this same issue with our on-premise TFS team room not being recognized as a "room". I've temporarily worked around it by downloading the latest code with the above fix, and loading it using the "Load Unpacked Extension" method described here https://github.com/nuts4dotnet/TFSChatExtensions/issues/2#issuecomment-158929619. Thanks for the helpful instructions!

Would it be possible to get a new release containing this fix available in Chrome webstore? This would be helpful as I'd like to recommend this plugin to my colleagues, but hesitate to ask them to go through the "Load Unpacked Extension" route. Thanks!

**Comment by jcoutch** [comment]
Hi Emily,

I apologize for not deploying these fixes sooner.  I just published the latest codebase as version 0.1.4 in the Chrome store...which may take an hour or two to propagate through their servers.  If you have the official plugin installed, it should update automatically.  Let me know if you run into any issues.

**Comment by eskitek** [comment]
Thank you!

**Pull request closed without merging**
